apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<github-username>/managed-argocd-lab' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: <environment-name> # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true